/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soalprakteklsp;

import java.util.Arrays;

/**
 *
 * @author BintangDiLangit
 */
public class Soal1 extends javax.swing.JFrame {

    /**
     * Creates new form Soal1
     */
    public Soal1() {
        initComponents();
        
        // agar ke tengah
        setLocationRelativeTo(this);

    }

    // mencari nilai genap
    public int genap(int angka[]) {
        int jumlah = 0;
        
        // looping untuk me run isi array
        for (int i = 0; i < angka.length; i++) {
            
            // mencari nilai genap
            if (angka[i] % 2 == 0) {
                jumlah++;
            }
        }
        
        // mengembalikan total nilai genap
        return jumlah;
    }

    // mencari nilai ganjil
    public int ganjil(int angka[]) {
        int jumlah = 0;
        for (int i = 0; i < angka.length; i++) {
            if (angka[i] % 2 == 1) {
                jumlah++;
            }
        }
        // mengembalikan total nilai ganjil
        return jumlah;
    }

    // mencari nilai prima
    public int prima(int angka[]) {
        String a = input.getText();

        String[] am = input.getText().split("");

        int size = am.length;
        int[] wow = new int[size];
        for (int i = 0; i < size; i++) {
            wow[i] = Integer.parseInt(am[i]);
        }
        int output = 0;
        boolean isPrime=true;
        
        for (int j = 0; j < wow.length; j++) {
            for (int i = 2; i < wow[j]; i++) {
                if (wow[j] % i == 0) {
                    isPrime = false;
                    break;
                }
            }

            if (isPrime) {
                
                output++;
            }
        }
        return output;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputan = new javax.swing.JLabel();
        genap = new javax.swing.JLabel();
        ganjil = new javax.swing.JLabel();
        prima = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input.setToolTipText("");
        input.setName(""); // NOI18N
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 176, -1));
        input.getAccessibleContext().setAccessibleName("");

        proses.setText("Process");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel1.setText("Angka yang diinputkan: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 64, -1, -1));

        jLabel2.setText("Jumlah bilangan genap: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 91, -1, -1));

        jLabel3.setText("Jumlah bilangan ganjil: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 124, -1, -1));

        jLabel4.setText("Jumlah bilangan prima:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 151, -1, -1));
        getContentPane().add(inputan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 64, 87, 20));
        getContentPane().add(genap, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 87, 20));
        getContentPane().add(ganjil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 87, 20));
        getContentPane().add(prima, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 87, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        
        // menjadikan array string ke array int
        String a = input.getText();

        String[] angka = input.getText().split("");

        int size = angka.length;
        int[] wow = new int[size];
        for (int i = 0; i < size; i++) {
            wow[i] = Integer.parseInt(angka[i]);
        }

        
        // mengubah ke string untuk dimasukkan ke masing2 label Jframe
        String gnp = String.valueOf(genap(wow));
        String gjl = String.valueOf(ganjil(wow));
        String prm = String.valueOf(prima(wow));

        String inputan2="";
        for (int i = 0; i < wow.length; i++) {
            inputan2 = String.valueOf(wow[i]);
        }
        
        inputan.setText(Arrays.toString(wow));
        
        genap.setText(gnp);
        ganjil.setText(gjl);
        prima.setText(prm);


    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ganjil;
    private javax.swing.JLabel genap;
    private javax.swing.JTextField input;
    private javax.swing.JLabel inputan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel prima;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
